### ISSUE TITLE
Atom is useless after changing theme in workflow 2.0

### ISSUE THREAD

**Issue by ljkania** [luna/luna-studio#274] opened 2017-09-11 15:46 UTC
Changing theme to other and going back to Luna Dark breaks view (i.e.: tabs view) and once you reload there is only white screen with this error in console:
```index.js:87 TypeError: Cannot read property 'numerator' of undefined
    at Node.Dimension.operate (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/tree/dimension.js:83:58)
    at Node.Operation.eval (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/tree/operation.js:31:18)
    at /Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/tree/call.js:31:54
    at Array.map (native)
    at Node.Call.eval (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/tree/call.js:31:26)
    at Node.Expression.eval (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/tree/expression.js:31:37)
    at Node.Value.eval (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/tree/value.js:18:30)
    at Node.Rule.eval (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/tree/rule.js:56:33)
    at Node.Ruleset.eval (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/tree/ruleset.js:149:50)
    at module.exports (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/transform-tree.js:67:22)
    at ParseTree.toCSS (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/parse-tree.js:14:25)
    at /Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/render.js:31:40
    at /Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/parse.js:63:17
    at Object.finish [as _finish] (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/parser/parser.js:183:28)
    at Object._onSequencerEmpty (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
    at ImportSequencer.tryRun (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
    at Object.run (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/visitors/import-visitor.js:29:25)
    at Object.parse (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/parser/parser.js:189:22)
    at Object.parse (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/parse.js:61:18)
    at Object.render (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less/lib/less/render.js:25:18)
    at /Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:318:27
    at LessCache.module.exports.LessCache.observeImportedFilePaths (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:200:15)
    at LessCache.module.exports.LessCache.parseLess (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:317:28)
    at LessCache.module.exports.LessCache.cssForFile (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:357:25)
    at LessCache.module.exports.LessCache.readFileSync (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:340:27)
    at LessCompileCache.module.exports.LessCompileCache.read (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/less-compile-cache.js:39:31)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/theme-manager.js:304:39)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/theme-manager.js:271:27)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/theme-manager.js:191:30)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/Users/LJK/Coding/Work/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/theme-manager.js:252:25)```

**Comment by piotrMocz** [comment] 2018-10-17 11:39
This is, in fact, a duplicate of https://github.com/luna/luna-studio/issues/512. Should be solved by new gui anyways.

**Closed by piotrMocz** 2018-10-17 11:39 UTC
Labels: P - Critical, T - Bug
