### ISSUE TITLE
Functions being displayed as nodes will get their names displayed without the last chars (Not constant)

### ISSUE THREAD

**Issue by TheOnlyArtz** [luna/luna-studio#1100] opened 2018-09-21 17:45 UTC
Watch as 3 functions are missing last character in the visual part vs the textual part
![image](https://user-images.githubusercontent.com/30025874/45897224-35a28480-bddf-11e8-853d-7f3c7977f04c.png)

EDIT: it looks like the only first function is the one to not being affected.

**Comment by jaen** [comment] 2018-09-22 12:05
Reproduction steps for me are (on 1.4.101.6):

1. create an empty project
2. paste this between imports and the `main` function:
```elm
class Test:
    TestCase:
        testField :: Int 

def test:
    "test"
```
The issue is probably with class case field parsing, since it does not seem to happen if the case has no fields.

**Comment by wdanilo** [comment] 2018-09-24 02:13
Should be fixed in https://github.com/luna/luna/pull/293

**Comment by piotrMocz** [comment] 2018-10-10 11:38
This is fixed in `1.5`.

**Comment by mikusp** [comment] 2018-10-10 11:39
This is fixed now

**Closed** 2018-10-10 11:38 UTC
Labels: C - Graph Editor, D - Unknown, P - High, S - Info Needed, T - Bug
