### ISSUE TITLE
Error while cloning tutorial

### ISSUE THREAD

**Issue by lgawlik** [luna/luna-studio#1010] opened 2018-07-29 20:34 UTC
1) Open USElectionPlayground
2) Go back to welcome screen
3) Open USElectionPlaygorun, there is an error: Error while cloning tutorial
![Errorwhilecloningtutorial.png](https://images.zenhubusercontent.com/5b15567389d5dc41604fd216/1a198ad5-f548-472b-8381-d0779243e993)

**Comment by mikusp** [comment] 2018-07-30 08:35
Duplicate of #1006

**Closed by mikusp** 2018-07-30 08:35 UTC
Labels: D - Core Contributor, P - High, T - Bug
