### ISSUE TITLE
Cryptocurrency server crash

### ISSUE THREAD

**Issue by Gurkenglas** [luna/luna-studio#756] opened 2018-01-21 19:59 UTC
@Gurkenglas commented on [Sun Jan 21 2018](https://github.com/luna/luna/issues/103)

A number of errors just requested I report them. I had, to my knowledge, merely been moving around nodes on the Cryptocurrency playground for a while.

![image](https://user-images.githubusercontent.com/1489801/35197570-70f75ef6-fee1-11e7-8511-1b92551d3884.png)

The logs that go to my clipboard and each open the github issues page (not the new issue page) follow.

Server crashed.

======= logs: =======

=== s-luna-empire.wrapper.log ===
2018-01-20 02:14:39,084 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-20 02:14:52,881 INFO  - Completed. Exit code is 0
2018-01-20 02:14:55,723 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-20 02:14:56,567 INFO  - Completed. Exit code is 0

LibraryNotFoundException "C:\\Users\\GURKEN~1\\AppData\\Local\\Temp\\luna\\tutorials\\CryptoCurrencyPlayground\\src\\Main.luna"

while processing event

empire.graph.node.updateMeta.response

======= logs: =======

=== s-luna-empire.wrapper.log ===
2018-01-20 02:14:39,084 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-20 02:14:52,881 INFO  - Completed. Exit code is 0
2018-01-20 02:14:55,723 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-20 02:14:56,567 INFO  - Completed. Exit code is 0

Cannot get file from backend

======= logs: =======

=== s-luna-empire.wrapper.log ===
2018-01-20 02:14:39,084 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-20 02:14:52,881 INFO  - Completed. Exit code is 0
2018-01-20 02:14:55,723 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-20 02:14:56,567 INFO  - Completed. Exit code is 0

**Comment by wdanilo** [comment] 2018-01-21 20:30
@Gurkenglas Thank you for reporting the issue. If you have any way to re-produce the errors, it would be much easier for us to discover them. I cannot reproduce it, but I'll keep it open for now so if somebody would be able to do so, we would be thankful for any further info here!

**Comment by kustosz** [comment] 2018-05-07 15:09
It should be fixed in newest versions, closing. Please reopen if the issue manifests itself again.

**Closed by kustosz** 2018-05-07 15:09 UTC
Labels: S - Info Needed, T - Bug
