### ISSUE TITLE
Cannot save TramsPlayground example

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna-studio#1254] opened 2018-11-07 13:11 UTC
I use luna-studio  1.5.100.94 

### Steps to Reproduce
1. Open the TramsPlayground example
1. Move focus to node editor
1. Presss Ctrl+S
1. Accept default path by Enter — I don't have anything in my filesystem under proposed path

### Expected Result
Project is saved at given path.

### Actual Result
Error appears:
```
C:\Users\mwurb\AppData\Local\Temp\luna13357\tutorials\TramsPlayground\: removeDirectoryRecursive:removeContentsRecursive:RemoveDirectory "\\\\?\\C:\\Users\\mwurb\\AppData\\Local\\Temp\\luna13357\\tutorials\\TramsPlayground\\": unsatisfied constraints (ディレクトリが空ではありません。)
CallStack (from -prof):

while processing event

empire.atom.project.move.response

======= logs: =======

=== s-luna-empire.err.log ===
ERROR 2018-11-07T13:02:53.8122235Z	:: error during processing request empire.atom.project.move.request: C:\Users\mwurb\AppData\Local\Temp\luna13357\tutorials\TramsPlayground\: removeDirectoryRecursive:removeContentsRecursive:RemoveDirectory "\\\\?\\C:\\Users\\mwurb\\AppData\\Local\\Temp\\luna13357\\tutorials\\TramsPlayground\\": unsatisfied constraints (ディレクトリが空ではありません。)
CallStack (from -prof):


=== s-luna-empire.out.log ===


=== s-luna-empire.wrapper.log ===
2018-11-07 14:02:17,700 INFO  - Starting ServiceWrapper in the CLI mode
2018-11-07 14:02:18,129 INFO  - Completed. Exit code is 0
```

The error message says that directory `C:\Users\mwurb\AppData\Local\Temp\luna13357\tutorials\TramsPlayground` is not empty. 
After I checked it later the directory exists and is empty.

Also, for some reason text editor and nodes disappeared. I cannot continue work (and lost any previous work that might have been done).
Also, the path where save was attempted, seemingly contains the project. I believe it shouldn't — if storing project fails, the directory should be restored to previous state. Now when I try to repeat this error, it fails because target path is already occupied.

### Luna Version

- Please include the output of `luna-studio --version`.
The command fails with the following:
![obraz](https://user-images.githubusercontent.com/1548407/48133165-3495bb80-e296-11e8-8c16-06120710d743.png)

In the console "Odmowa dostępu." (access denied) is written, even if running command prompt with administrator privileges.

**Comment by mwu-tow** [comment] 2018-11-07 13:30
It actually affects saving all new project, including the default new project template.

**Comment by iamrecursion** [comment] 2018-11-07 14:51
This may be a violated precondition check. It shouldn't have deleted everything until the move was successful.

**Comment by mwu-tow** [comment] 2018-11-07 15:55
Using shell commands for project renaming looks ok:
```
F:\dev\temp>luna init Test
Initialised package at F:\dev\temp\Test

F:\dev\temp>luna rename Test Test2
Package renamed to F:\dev\temp\Test2\

F:\dev\temp>ls
Test2

F:\dev\temp>
```

**Comment by iamrecursion** [comment] 2018-11-08 09:48
I think this might be two issues in one. 

1. Some code, somewhere, is hanging onto the folder. If it's owned on windows it can't be deleted. This doesn't look like it is caused by either `Package.rename` or any of the logic in `Package.Generate`. 
2. Something _else_ is causing work to be lost in this situation. @mikusp does LS save to the original location before it's renamed?

**Comment by iamrecursion** [comment] 2018-11-08 15:19
This is now hopefully fixed on master.

**Comment by iamrecursion** [comment] 2018-11-09 12:44
Again now hopefully fixed on master.

**Comment by sylwiabr** [comment] 2018-11-13 15:14
There is something strange going on: it happens sometimes but not always and is nondeterministic.

**Comment by iamrecursion** [comment] 2018-11-13 15:16
So it still happens with the fix?

**Comment by mwu-tow** [comment] 2018-11-13 15:19
The saving still is broken but I have not seen again the error messages that are described in the first post. Still trying to understand what is happening and when.

**Comment by sylwiabr** [comment] 2018-11-13 15:32
I've got this one: 
![img_20181113_162250](https://user-images.githubusercontent.com/12892578/48423768-8be9cf00-e761-11e8-8c29-f0d13bb517c5.jpg)
@mikusp commented that it is caused by the fact that file disappears while processing searcher hints (am I right @mikusp ?)

**Comment by mwu-tow** [comment] 2018-11-13 15:35
Appeared again, this:
![obraz](https://user-images.githubusercontent.com/1548407/48424098-2ea24d80-e762-11e8-824e-198dc8915e9d.png)

**Comment by sylwiabr** [comment] 2018-11-13 15:36
saving tutorial ends with
![img_20181113_163336](https://user-images.githubusercontent.com/12892578/48424151-4f6aa300-e762-11e8-86ef-b582cbbd5299.jpg)

**Comment by iamrecursion** [comment] 2018-11-13 15:37
A lot of this now looks like it's not updating to the moved location properly.

**Comment by mwu-tow** [comment] 2018-11-14 17:14
@mikusp 
Just tested 1.5.100.113 package and unfortunately the problem persists:
Steps: create a new project, attempt save at a new location, result: 
![obraz](https://user-images.githubusercontent.com/1548407/48499563-ffaadb00-e838-11e8-8a21-4fdee500a096.png)
And node editor is not functional anymore (pressing Tab does nothing).

**Closed** 2018-11-15 15:02 UTC
Labels: D - Core Contributor, P - Critical, T - Bug
