### ISSUE TITLE
Error Cloning Tutorial (Windows 10)

### ISSUE THREAD

**Issue by Charon77** [luna/luna-studio#764] opened 2018-01-23 06:49 UTC
Just finished installing LunaStudio 1.0 on Windows 10 x64

Running this as normal user results:

![image](https://user-images.githubusercontent.com/1199566/35261587-69d0e1c0-0043-11e8-8523-82fc14a2cc96.png)

Running as admin works without a prob

**Comment by pmlodawski** [comment] 2018-01-23 09:20
Hello @Charon77, thanks for your bug report!

This actually works without administrator rights on windows. Do you have a proxy or some custom firewall?

**Comment by Charon77** [comment] 2018-01-23 12:19
@pmlodawski Hi,
no I don't use any proxy, and I have my firewall (windows, my only firewall) disabled (at all times)

v1.0.1 also produces the same error.

**Comment by piotrMocz** [comment] 2018-01-23 20:48
Hey @pmlodawski, a user has just reached out with an issue during the tutorials download, so I'm attaching [the screenshot here](https://cdn.discordapp.com/attachments/401739816108163073/405461992007008257/unknown.png) and leave it up to you to decide whether that deserves a separate bug, or you're able to fix them both with one PR :)

**Comment by SalvorinFex** [comment] 2018-01-24 02:38
I am getting the same error and I am signed in with an MS account, if that makes any difference or not.

**Comment by pmlodawski** [comment] 2018-01-24 09:37
@Charon77 the first error looks like internet connectivity problem, we could test extending timeout and see what happens there.

About the second screenshot, attached by @piotrMocz :
@Charon77 , I think testing this as admin resulted in creating  `C:\Users\avica\AppData\Local\Temp\luna` with administrator permissions and now, when running luna with normal user permissions, we have issues with moving around files there. Can you try remove this folder and try again as normal user?

**Comment by pmlodawski** [comment] 2018-01-24 09:38
@SalvorinFex you are talking about **ETIMEDOUT** error or **EPERM** one?

**Comment by pmlodawski** [comment] 2018-01-24 09:52
@Charon77, @SalvorinFex: if **ETIMEDOUT** persist, we could try if removing timeout will help:
1. close luna-studio
2. go into `C:\Users\YOUR_USER\.luna\config\luna-studio\1.0.2\atom\packages\luna-studio\lib`
3. open `projects.coffee`
4. find
    ``` 
    mkRequestOpts = (url) ->
        url: url
        timeout: 10000
        headers: 
            'User-Agent': 'luna-studio'
    ```
5. remove whole line with `timeout: 10000` 
6. save, and open luna-studio again

**Comment by Charon77** [comment] 2018-01-24 11:17
First of all, I'd like to add that running luna-studio (1.0 and 1.0.1) __without__ admin results in this in the welcome screen.
![image](https://user-images.githubusercontent.com/1199566/35329383-4235aee4-0132-11e8-9e99-f143fad52311.png)

Running as admin (almost immediately) displays the proper thumbnail.

I've tried deleting `C:\Users\<USER>\AppData\Local\Temp\luna` and running it but still same result.

Lastly, I've tried deleting the `timeout: 10000` from said file, line 32, and then delete the `Temp\luna`  folder, still no luck.

Weird enough I still got the same error

![image](https://user-images.githubusercontent.com/1199566/35329502-acf97ea4-0132-11e8-90e9-e3265c8eed14.png)

I've doubled checked, and yes, I have saved the file, I've run the program twice.

Maybe a debugging output would help but I don't know how to enable / view it.

Cheers 🍺

**Comment by Charon77** [comment] 2018-01-24 11:22
For completeness, this is what I see when I run the program __with__ admin.

![image](https://user-images.githubusercontent.com/1199566/35329737-7d64b310-0133-11e8-94d6-1fd0709ee4cd.png)

It seems the problem arises __before__ I even clicked any of the tutorial. So, if there's no thumbnail, there's certainly a problem...

**Comment by pmlodawski** [comment] 2018-01-24 11:41
Thanks for all the screenshots, now its really easier to see what happens. 

That's very strange that **luna-studio** is showing an error about connecting to local address `10.0.0.2` on that strange port `808`. **Can you try to find what is hiding under this address?** All this request should be addressed to github, not some local addresses. 

When downloading tutorial list `luna-studio` connects to 
`https://api.github.com/orgs/luna-packages/repos` 
and later on to 
`https://api.github.com/repos/luna-packages/`**project_name**`/contents/thumb.png` to download thumbnails. Downloading tutorials is also request to github: 
`https://api.github.com/repos/luna-packages/`**project_name**`/zipball/master`
You can test if this addresses works for you in browser

**Comment by mikusp** [comment] 2018-01-24 11:45
@pmlodawski I think the error is truncated, and the port is 8088 - our websocket

**Comment by Charon77** [comment] 2018-01-24 12:29
@pmlodawski 
I'm quite certain this is not a connectivity issue since

1. I can run the program normally under admin
2. I can connect to all three url you give.

@mikusp I've tried manually starting the services, since strangely, they don't run. After making sure the services run, running luna-studio takes a long time, and would say something like it's not responding. (If I'm running admin, the program sometimes will tell that it's not responding too)

Still, it doesn't load the thumbnail nor the tutorials.

![image](https://user-images.githubusercontent.com/1199566/35332165-9236ac90-013c-11e8-9a2e-607e5eb2f9b7.png)

**Comment by mikusp** [comment] 2018-01-24 12:35
@Charon77 starting with version 1.0.2 the services are only running while Luna Studio is opened

**Comment by pmlodawski** [comment] 2018-01-24 12:44
That shouldn't be connected with services at all. Downloading tutorial list and tutorials themselves doesn't interact with backend

**Comment by Charon77** [comment] 2018-01-24 14:18
Hey, I've just installed 1.0.2 and the problem persists.

I could try these, but hadn't known how:
1. Full uninstall of Luna (studio, manager, everything related)
2. Enable debugging (does such feature exists, and how can I enable them?)

**Comment by pmlodawski** [comment] 2018-01-24 14:33
@Charon77 please check what `10.0.0.2` is and what in your system can forward traffic there. 
Maybe try pinging `api.github.com` from console (non admin), also ping `10.0.0.2`. Did you try if links I provided above work for you?

Firewall or other your system tools may work different for admin and for normal user

**Comment by Charon77** [comment] 2018-01-24 16:17
Hi @pmlodawski 

![image](https://user-images.githubusercontent.com/1199566/35343024-2aa07122-015c-11e8-8afd-1fb0ae8e1a35.png)

My computer doesn't run in the 10.x.x.x segment, does any device in my house. 

About the links:

1.
![image](https://user-images.githubusercontent.com/1199566/35343130-65b01092-015c-11e8-82ea-057c094477b3.png)

2.
![image](https://user-images.githubusercontent.com/1199566/35343193-92d607ca-015c-11e8-977c-1912a0bbe71a.png)

3rd one prompts download, so it works.

**Comment by Charon77** [comment] 2018-01-25 09:11
Dear @pmlodawski 
I am __truly sorry__ as turns out I was not checking whether I am using a proxy or not, whereas in fact I did.

This is very embarrassing for me to not have figured that out earlier, and I want to apologize for the inconvenience.

Indeed it was pointing to an incorrect proxy address. After turning it off, I can run download and run the tutorial without problems.

That being said, thank you very much for helping me figuring this out.

**Comment by pmlodawski** [comment] 2018-01-25 09:35
No problem, I'm glad that it finally works!

**Comment by SalvorinFex** [comment] 2018-01-27 06:33
Sorry for the late reply, but I am still having this issue.

![luna cloning error](https://user-images.githubusercontent.com/2433369/35469415-e7d8103c-02e8-11e8-83ca-59141a66abc5.jpg)

This happens in either as the user or as admin.

```
Connection closed.

======= logs: =======

=== s-luna-empire.err.log ===


=== s-luna-empire.out.log ===


=== s-luna-empire.wrapper.log ===
2018-01-23 17:55:01,704 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 17:55:02,167 INFO  - Completed. Exit code is 0
2018-01-23 18:00:27,888 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:00:28,196 INFO  - Completed. Exit code is 0
2018-01-23 18:08:33,428 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:08:33,810 INFO  - Completed. Exit code is 0
2018-01-23 18:13:08,231 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:13:08,478 INFO  - Completed. Exit code is 0
2018-01-23 18:13:39,000 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:13:39,380 INFO  - Completed. Exit code is 0
2018-01-23 18:16:12,847 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:16:13,064 INFO  - Completed. Exit code is 0
2018-01-23 18:26:38,621 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:26:38,979 INFO  - Completed. Exit code is 0
2018-01-23 18:30:09,935 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:30:10,218 INFO  - Completed. Exit code is 0
2018-01-23 18:30:56,799 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:30:57,176 INFO  - Completed. Exit code is 0
2018-01-23 18:31:27,947 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:31:28,273 INFO  - Completed. Exit code is 0
2018-01-23 18:51:32,328 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:51:32,701 INFO  - Completed. Exit code is 0
2018-01-23 18:52:03,726 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:52:03,989 INFO  - Completed. Exit code is 0
2018-01-26 22:13:28,840 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:13:29,451 INFO  - Completed. Exit code is 0
2018-01-26 22:15:41,224 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:15:41,548 INFO  - Completed. Exit code is 0
2018-01-26 22:15:45,389 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:15:45,842 INFO  - Completed. Exit code is 0
2018-01-26 22:16:48,761 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:16:49,086 INFO  - Completed. Exit code is 0
2018-01-26 22:17:48,537 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:17:48,958 INFO  - Completed. Exit code is 0
```
This is the paste from the red box that pops up after I click on OK.

![luna net config](https://user-images.githubusercontent.com/2433369/35469402-b231c6e4-02e8-11e8-818b-8b0ef5c1113e.jpg)

Here are my network config settinngs.

**Comment by wdanilo** [comment] 2018-02-01 20:34
@SalvorinFex I'm sorry, we had to miss your message somehow. I'll reopen the issue and Im sure @pmlodawski will take a look at it asap! :)

**Comment by SalvorinFex** [comment] 2018-02-01 21:42
Alright, Thank you.

**Comment by pmlodawski** [comment] 2018-02-02 08:41
@SalvorinFex, EPERM error is caused by running application with administrator rights. After that some folders created by admin cannot be moved by normal user. 
1. Please close luna-studio,
2. remove `C:\Users\`__YOUR_USER__`\AppData\Local\Temp\luna`. Reboot may also be helpful.

If you will get any other error please paste it here.

**Comment by wdanilo** [comment] 2018-02-02 18:59
I'll close this issue, @SalvorinFex if youll encounter any further problems, feel free to reopen it :)

**Comment by SalvorinFex** [comment] 2018-02-03 02:56
Hello again, I followed your 3 instructions and I am getting the same thing.
I am logged in with am MS account so, by default I am an admin.

```
Connection closed.

======= logs: =======

=== s-luna-empire.err.log ===


=== s-luna-empire.out.log ===
Requested module: Std.Base
Compiling module: Std.Base
Requested module: Std.HTTP
Compiling module: Std.HTTP
Requested module: Std.System
Compiling module: Std.System
Requested module: Std.Time
Compiling module: Std.Time
Requested module: Std.WebSockets
Compiling module: Std.WebSockets


=== s-luna-empire.wrapper.log ===
2018-01-23 17:55:01,704 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 17:55:02,167 INFO  - Completed. Exit code is 0
2018-01-23 18:00:27,888 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:00:28,196 INFO  - Completed. Exit code is 0
2018-01-23 18:08:33,428 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:08:33,810 INFO  - Completed. Exit code is 0
2018-01-23 18:13:08,231 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:13:08,478 INFO  - Completed. Exit code is 0
2018-01-23 18:13:39,000 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:13:39,380 INFO  - Completed. Exit code is 0
2018-01-23 18:16:12,847 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:16:13,064 INFO  - Completed. Exit code is 0
2018-01-23 18:26:38,621 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:26:38,979 INFO  - Completed. Exit code is 0
2018-01-23 18:30:09,935 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:30:10,218 INFO  - Completed. Exit code is 0
2018-01-23 18:30:56,799 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:30:57,176 INFO  - Completed. Exit code is 0
2018-01-23 18:31:27,947 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:31:28,273 INFO  - Completed. Exit code is 0
2018-01-23 18:51:32,328 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:51:32,701 INFO  - Completed. Exit code is 0
2018-01-23 18:52:03,726 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-23 18:52:03,989 INFO  - Completed. Exit code is 0
2018-01-26 22:13:28,840 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:13:29,451 INFO  - Completed. Exit code is 0
2018-01-26 22:15:41,224 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:15:41,548 INFO  - Completed. Exit code is 0
2018-01-26 22:15:45,389 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:15:45,842 INFO  - Completed. Exit code is 0
2018-01-26 22:16:48,761 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:16:49,086 INFO  - Completed. Exit code is 0
2018-01-26 22:17:48,537 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:17:48,958 INFO  - Completed. Exit code is 0
2018-01-26 22:18:51,074 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:18:51,392 INFO  - Completed. Exit code is 0
2018-01-26 22:18:55,794 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:18:56,265 INFO  - Completed. Exit code is 0
2018-01-26 22:22:20,735 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:22:21,066 INFO  - Completed. Exit code is 0
2018-01-26 22:22:28,351 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:22:28,799 INFO  - Completed. Exit code is 0
2018-01-26 22:22:56,858 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:22:57,249 INFO  - Completed. Exit code is 0
2018-01-26 22:24:46,560 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:24:47,118 INFO  - Completed. Exit code is 0
2018-01-26 22:25:49,430 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:25:49,717 INFO  - Completed. Exit code is 0
2018-01-26 22:36:23,175 INFO  - Starting ServiceWrapper in the CLI mode
2018-01-26 22:36:23,696 INFO  - Completed. Exit code is 0
2018-02-02 18:46:51,478 INFO  - Starting ServiceWrapper in the CLI mode
2018-02-02 18:46:51,958 INFO  - Completed. Exit code is 0

```

**Comment by SalvorinFex** [comment] 2018-02-05 03:17
Hello, I am just wondering if you have had a chance to look into this?
Do you need anything else from me?

**Comment by pmlodawski** [comment] 2018-02-05 06:59
@SalvorinFex this error is about permissions to write to destination folder. If you removed it and it does not exist, Luna Studio should be able to create it. I Don't know what is happening but I will try to reproduce it. 

Before I will find a solution you can test our examples manually downloading them from here https://github.com/luna-packages and opening them in Luna Studio by pressing __Ctrl-Shift-O__

**Comment by SalvorinFex** [comment] 2018-02-06 19:34
@pmlodawski Okay, 2 things worked, both opening the file manually and after updating to 1.1 also worked.

So, this can be closed.

**Comment by pmlodawski** [comment] 2018-02-07 15:12
Good to hear that!

**Comment by michaelteter** [comment] 2018-06-16 07:27
I have the same problem as SalvorinFex, and I am running 1.2.0.2.

**Comment by wdanilo** [comment] 2018-06-17 13:16
@michaelteter The issue was closed because both solutions worked - openning the file manually as well as updating to 1.1 (without manual openning then). We haven't seen this error for a while. @pmlodawski could you please take a look here?

**Comment by michaelteter** [comment] 2018-06-17 15:36
Thanks for the attention @wdanilo .  I'm on Windows 10 Pro, Version	10.0.17134 Build 17134.  32GB RAM and other relatively high-end stats on the hardware.

When I try to open a tutorial, the popup informational window title is LunaStudio 1.2.0.2.  The error is "Error while cloning tutorial", and the message is
Cannot open tutorial: EPERM: operation not permitted, rename
'C:\Users\mteter\AppData\Local\Temp\lun...\luna-packages-USElectionPlayground-8a86b3d'
-> 'C:\Users\mteter\AppData\Local\Temp\luna16977\tutorials\USElectionPlayground'

My user is the owner of the Temp folder, and despite Explorer showing the folder as Read Only, the security details show that my user has full read/write/access rights to that Temp folder.

Yes, manually cloning via Git and then manually opening the new project folder in Atom/Luna does work, but obviously this is a workaround rather than a solution.

I thought I had previously tried running Luna as administrator, but apparently I had not; I just tried running Luna as Administrator, and it was then able to download and open the Election tutorial without a problem.  

Could you just use a temp folder under the current user, but NOT in the AppData\Local\Temp (which apparently has weird permissions)?  I don't think it's generally good to have to run apps and tools as admin... and people in corporate environments who want to explore Luna will have to ask their IT departments for permission (and we know how that usually goes...)

**Comment by wdanilo** [comment] 2018-06-17 15:40
@michaelteter thanks for an awesome description! You should never ever run any application as administrator, even if you trust it very much. It just breakes very important rules between users and app providers. We'll talk about it and @pmlodawski will be back to you here!

**Comment by michaelteter** [comment] 2018-07-03 22:32
@SalvorinFex - I'm definitely not a Windows guy, but I can confirm my user account is a local Administrator.

**Closed** 2018-07-25 10:07 UTC
Labels: S - Info Needed, T - Bug

**Comment by vladimiry** [comment] 2018-07-27 15:16
EPERM errors often occur when there is a frequent file operations happening (even read access), some [details](https://github.com/isaacs/node-graceful-fs/pull/119#issuecomment-346711384). So it's unlikely that running app with admin role will help a lot in mitigating such kind of errors.
