### ISSUE TITLE
The `unsaved-luna-project` default name selection is not visible when saving the project.

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#606] opened 2018-01-03 15:47 UTC
The name behaves like it is selected, it smells like it is selected, but doesn't look selected.

**Comment by pmlodawski** [comment] 2018-01-22 14:24
It looks like Mac issue. Here is how it looks on Linux:
![image](https://user-images.githubusercontent.com/5347572/35225316-3f896e02-ff88-11e7-965d-1b086734d730.png)

**Comment by mikusp** [comment] 2018-04-04 13:57
Duplicate of #389

**Closed by mikusp** 2018-04-04 13:57 UTC
