### ISSUE TITLE
Case for broken undo–redo

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#1044] opened 2018-08-14 09:03 UTC
1. Open new project
2. Select the existing node
3. Add `reverse` node
4. Add another `reverse` node
5. Undo twice
6. With the `test` node selected, add `reverse` node.
7. Undo.
8. Redo twice.
It results in a strange state, see video in the comment. It is also worth noting that the longer you use Luna Studio and randomly undo–redo actions, you can get all sorts of strange results (including some exceptions like BreadcrumbDoesNotExist), these are however much less predictable and harder to reproduce.

**Comment by kustosz** [comment] 2018-08-14 09:04
Repro video https://drive.google.com/open?id=1kT3Wqsec9pf_A6NpnIqVdXqfffVvSCPv

**Comment by piotrMocz** [comment] 2018-09-24 16:15
I'm seeing a different (albeit still not desired, I guess) behaviour: step 8. allows me to only do one "Redo", leaving the node in a greyed-out state and preventing any further actions. If I go up to the top-level and back to `main`, it gets the type and the result. Please see the video for reference (and please pardon the notification popping up towards the end ;))

https://drive.google.com/file/d/1Tj23w3aYHpPXKftM_v5Cqh0Yy15MNcvf/view?usp=sharing

I'm moving this task back to `In Progress` -- maybe I'm wrong and maybe that's a different task altogether. @mikusp feel free to close it and open another one, if needed.

**Comment by mikusp** [comment] 2018-10-04 14:35
Redoing only once is correct. However, the node should be typechecked so I'll move that to backlog and see what's going on.

**Comment by mikusp** [comment] 2018-10-15 12:40
We can't reproduce this issue

**Closed by mikusp** 2018-10-15 12:40 UTC
Labels: C - Graph Editor, D - Core Contributor, P - High, T - Bug
