### ISSUE TITLE
installer.exe does not open installer at all

### ISSUE THREAD

**Issue by ShadedJockey** [luna/luna-studio#776] opened 2018-01-27 13:01 UTC
As the title says.

Windows 10 Pro (Version 1709)(OS Build 16299.192)
64-bit operating system
i7-6700k 
RAM 8.00gb

**Comment by mhhegazy** [comment] 2018-01-27 23:41
same here

OS: Windows 10 Home (Version 1709)(OS Build 16299.192) 64-bit
CPU: i7-6500U
RAM: 16.0 GB

**Comment by wdanilo** [comment] 2018-01-29 03:42
@ShadedJockey , @mhhegazy could you please using the cmd installer (you can download it from our website). Just open terminal and execute it. Please tell me if it worked. We've got some reports about gui installer not showing up, were investigating it.

**Comment by sylwiabr** [comment] 2018-01-29 09:05
duplicate of https://github.com/luna/installer-electron/issues/21

**Closed by sylwiabr** 2018-01-29 09:05 UTC
Labels: bug, duplicate
